version: "3.8"

services:
  postgres:
    image: "postgres:14-alpine"
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  covid-tracker:
    image: stuetz/covid-tracker:1.0.0
    ports:
      - '8080:8080'
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/db
    depends_on:
      - postgres